/* ============================================================
   FX.01 v1.3.0 — Completo Corrigido — GitHub Actions Ready
   - 7 etapas cadastro (usuario/senha/nome/recuperação/salario/adiant/ciclo/categorias)
   - 3 temas + claro/escuro persistente
   - Criptografia AES-GCM 150k + fallback
   - 27 bugs corrigidos
   ============================================================ */
"use strict";
const FX_VERSION="FX.01-v1.3.0"; const STORAGE_KEY="fx01_data";
const CATEGORY_ICONS={ fixed:`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`, reserve:`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="12" x="2" y="6" rx="2"/><circle cx="12" cy="12" r="2"/></svg>`, medicine:`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m10.5 20.5 10-10a4.95 4.95 0 1 0-7-7l-10 10a4.95 4.95 0 1 0 7 7Z"/><path d="m8.5 8.5 7 7"/></svg>`, leisure:`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="12" x="2" y="6" rx="6"/></svg>`, phone:`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="20" x="5" y="2" rx="2"/><line x1="12" x2="12.01" y1="18" y2="18"/></svg>`, other:`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/></svg>`, biometrics:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 11c0 3.517-1.009 6.799-2.753 9.571m-3.44-2.04C4.05 16.148 3 13.686 3 11c0-4.97 4.03-9 9-9s9 4.03 9 9c0 4.015-2.631 7.41-6.284 8.571M12 7v8m0 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/></svg>`};
const SVG_EYE_OPEN=`<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg>`; const SVG_EYE_SLASH=`<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9.88 9.88a3 3 0 1 0 4.24 4.24"/><path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68"/><path d="M6.61 6.61A13.52 13.52 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61"/><line x1="2" x2="22" y1="2" y2="22"/></svg>`;
function getCategoryIconSvg(cat){ if(cat&&CATEGORY_ICONS[cat.icon]) return CATEGORY_ICONS[cat.icon]; if(cat&&CATEGORY_ICONS[cat.id]) return CATEGORY_ICONS[cat.id]; return CATEGORY_ICONS.other; }
const DEFAULT_CATEGORIES=[{id:"fixed",name:"Gasto Fixo",icon:"fixed",hasLimit:false,limit:null,protected:true},{id:"reserve",name:"Reserva",icon:"reserve",hasLimit:false,limit:null,protected:true,immutable:true},{id:"medicine",name:"Medicamentos",icon:"medicine",hasLimit:false,limit:null,protected:true},{id:"leisure",name:"Lazer",icon:"leisure",hasLimit:false,limit:null,protected:true},{id:"phone",name:"Telefone / Internet",icon:"phone",hasLimit:false,limit:null,protected:true},{id:"other",name:"Outros",icon:"other",hasLimit:false,limit:null,protected:true}];
// SECURITY - fix btoa + try/catch + 150k
async function hashPassword(p){ if(!p) return ""; const d=new TextEncoder().encode(p); const h=await crypto.subtle.digest("SHA-256",d); return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,"0")).join(""); }
async function getCryptoKey(p,s){ const enc=new TextEncoder(); const m=await crypto.subtle.importKey("raw",enc.encode(p),{name:"PBKDF2"},false,["deriveKey"]); return crypto.subtle.deriveKey({name:"PBKDF2",salt:s,iterations:150000,hash:"SHA-256"},m,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]); }
async function encryptData(t,p){ const enc=new TextEncoder(); const salt=crypto.getRandomValues(new Uint8Array(16)); const iv=crypto.getRandomValues(new Uint8Array(12)); const k=await getCryptoKey(p,salt); const en=await crypto.subtle.encrypt({name:"AES-GCM",iv},k,enc.encode(t)); const comb=new Uint8Array(salt.length+iv.length+en.byteLength); comb.set(salt,0); comb.set(iv,salt.length); comb.set(new Uint8Array(en),salt.length+iv.length); let bin=""; comb.forEach(b=>bin+=String.fromCharCode(b)); return btoa(bin); }
async function decryptData(c,p){ try{ const bin=atob(c); const comb=Uint8Array.from(bin,ch=>ch.charCodeAt(0)); const salt=comb.slice(0,16); const iv=comb.slice(16,28); const d=comb.slice(28); const k=await getCryptoKey(p,salt); const dec=await crypto.subtle.decrypt({name:"AES-GCM",iv},k,d); return new TextDecoder().decode(dec);}catch(e){ throw new Error("Senha incorreta ou backup corrompido."); } }
function validateBackupSchema(d){ if(!d||typeof d!=="object") throw new Error("Estrutura inválida."); if(!d.version||typeof d.version!=="string") throw new Error("Versão ausente."); if(typeof d.setupCompleted!=="boolean") throw new Error("Estado inválido."); if(!d.user||typeof d.user!=="object") throw new Error("Usuário corrompido."); if(!Array.isArray(d.categories)) throw new Error("Categorias corrompidas."); if(!Array.isArray(d.cycles)) throw new Error("Ciclos corrompidos."); }
function escapeHTML(s){ return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;"); }

let state=null; let currentCategoryId=null; let currentEditingCategoryId=null; let currentEditingExpenseId=null; let currentSetupStep=1; let setupSalarySplit=null; let setupCategories=[]; let settingsSalarySplit=null; let categoryEditorHasLimit=false; let selectedReserveOrigin=null; let selectedExpenseOrigin="salary"; let selectedEditExpenseOrigin="salary"; let selectedEditExpenseCategory="fixed"; let selectedCategoryIcon="other"; let editingSetupCategoryIndex=null; let setupLimitHasLimit=false; let currentScreenName="main"; let currentTabName="home"; let customConfirmCallback=null;
const $=id=>document.getElementById(id);
const screens={ setup:$("setup-screen"), lock:$("lock-screen"), main:$("main-screen"), settings:$("settings-screen") };

document.addEventListener("DOMContentLoaded",()=>{ bindEvents(); setupAndroidNavigation(); applyThemeFromStorage(); loadApplication(); });
function setupAndroidNavigation(){ window.addEventListener("popstate",()=>handleBackAction()); if(window.Capacitor?.Plugins?.App){ window.Capacitor.Plugins.App.addListener('backButton',()=>handleBackAction()); } }
function handleBackAction(){ const openModals=document.querySelectorAll('.modal:not(.hidden)'); if(openModals.length>0){ const last=openModals[openModals.length-1]; last.classList.add('hidden'); try{ history.back(); }catch{} return; } if(currentScreenName==="settings"){ showScreen("main",false); return; } if(currentScreenName==="main"&&currentTabName==="extrato"){ switchTab("home",false); return; } if(currentScreenName==="main"){ if(state&&!state.security.locked){ lockApp(); } else if(window.Capacitor?.Plugins?.App){ window.Capacitor.Plugins.App.exitApp(); } } }
function pushNavigationState(t,n){ try{ history.pushState({type:t,name:n},""); }catch{} }
function applyThemeFromStorage(){ const ap=localStorage.getItem("fx_appearance")||"dark"; const th=localStorage.getItem("fx_theme")||"theme1"; document.documentElement.setAttribute("data-appearance",ap); document.documentElement.setAttribute("data-theme",th); }
function saveAppearance(ap){ localStorage.setItem("fx_appearance",ap); document.documentElement.setAttribute("data-appearance",ap); renderApplication(); renderPersonalization(); }
function saveTheme(th){ localStorage.setItem("fx_theme",th); document.documentElement.setAttribute("data-theme",th); renderApplication(); renderPersonalization(); }
async function saveState(){ if(!state) return; try{ const json=JSON.stringify(state); const key=state.security.passwordHash?state.security.passwordHash.slice(0,16):"fx01-default-key"; const enc=await encryptData(json,key); localStorage.setItem(STORAGE_KEY,enc); }catch(e){ try{ if(e.name==="QuotaExceededError") customAlert("Armazenamento cheio. Exporte backup e limpe histórico."); localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); }catch{} } }
async function loadApplication(){
  const stored=localStorage.getItem(STORAGE_KEY);
  if(!stored){ startInitialSetup(); return; }
  try{
    let jsonStr=stored;
    if(!stored.trim().startsWith("{")){
      const possibleKey = localStorage.getItem("fx_temp_key")||"";
      if(possibleKey){ try{ jsonStr=await decryptData(stored,possibleKey);}catch{ jsonStr=stored; } }
      else { startInitialSetup(); return; }
    }
    const parsed=JSON.parse(jsonStr);
    state=(parsed&&typeof parsed==="object")?parsed:createEmptyState();
  }catch{ state=createEmptyState(); }
  normalizeState(); checkCycleRollover(); checkCycleNotification();
  if(!state.setupCompleted){ startInitialSetup(); return; }
  if(state.security&&state.security.locked){ lockApp(); return; }
  showScreen("main",false); renderApplication();
}
function normalizeState(){
  if(!state||typeof state!=="object") state=createEmptyState();
  if(!state.user||typeof state.user!=="object") state.user={fullName:"",displayName:"",username:""};
  if(!state.user.username) state.user.username=state.user.username||"";
  if(!state.user.fullName) state.user.fullName=state.user.name||"Titular";
  if(!state.user.displayName) state.user.displayName=state.user.fullName.split(" ")[0]||"Titular";
  if(!Array.isArray(state.categories)) state.categories=[];
  // merge new default categories if version changed
  DEFAULT_CATEGORIES.forEach(def=>{ if(!state.categories.find(c=>c.id===def.id)) state.categories.push({...def}); });
  if(!Array.isArray(state.cycles)) state.cycles=[];
  if(!state.currentCycle) state.currentCycle=null;
  if(!state.reserve) state.reserve={balance:0}; state.reserve.balance=roundMoney(state.reserve.balance||0);
  if(!state.salary) state.salary={reference:0,hasAdvance:false,advanceAmount:0,advanceDay:20}; state.salary.reference=roundMoney(state.salary.reference||0); state.salary.advanceAmount=roundMoney(state.salary.advanceAmount||0);
  if(!state.extra) state.extra={balance:0}; state.extra.balance=roundMoney(state.extra.balance||0);
  if(!state.security) state.security={passwordHash:"",locked:false,lastCycleNotificationDate:"",biometricId:null,biometricType:null,recoveryQuestion:"",recoveryAnswerHash:""};
  if(state.security.recoveryQuestion===undefined) state.security.recoveryQuestion=""; if(state.security.recoveryAnswerHash===undefined) state.security.recoveryAnswerHash="";
  if(!state.settings) state.settings={cycleDay:5,hideBalances:false};
  if(!state.settings.cycleDay) state.settings.cycleDay=5;
  if(state.settings.hideBalances===undefined) state.settings.hideBalances=false;
  state.version=FX_VERSION;
  normalizeCycle(state.currentCycle); state.cycles.forEach(normalizeCycle);
}
function normalizeCycle(cycle){ if(!cycle) return; if(!Array.isArray(cycle.expenses)) cycle.expenses=[]; if(!Array.isArray(cycle.transfers)) cycle.transfers=[]; if(!cycle.categoryUsage) cycle.categoryUsage={}; cycle.salaryReceived=roundMoney(cycle.salaryReceived||0); cycle.leftoverSalary=roundMoney(cycle.leftoverSalary||0); if(state&&Array.isArray(state.categories)){ state.categories.forEach(cat=>{ let total=0; cycle.expenses.forEach(exp=>{ if(exp.categoryId===cat.id) total+=Number(exp.amount)||0; }); cycle.categoryUsage[cat.id]=roundMoney(total); }); } }
function createEmptyState(){ return {version:FX_VERSION,setupCompleted:false,user:{username:"",fullName:"",displayName:""},security:{passwordHash:"",locked:false,lastCycleNotificationDate:"",biometricId:null,biometricType:null,recoveryQuestion:"",recoveryAnswerHash:""},salary:{reference:0,hasAdvance:false,advanceAmount:0,advanceDay:20},extra:{balance:0},reserve:{balance:0},settings:{cycleDay:5,hideBalances:false},categories:[],cycles:[],currentCycle:null}; }
function checkCycleNotification(){ if(!state||!state.currentCycle||!state.currentCycle.endDate) return; if(!("Notification" in window)) return; const now=new Date(); const end=new Date(state.currentCycle.endDate); const diff=Math.ceil((end-now)/86400000); if(diff>0&&diff<=3){ const today=now.toISOString().slice(0,10); if(state.security.lastCycleNotificationDate!==today){ if(Notification.permission==="granted"){ new Notification("FX — Aviso de Fechamento",{body:`Seu ciclo encerra em ${diff} ${diff===1?'dia':'dias'}.`}); state.security.lastCycleNotificationDate=today; saveState(); } } } }
function checkCycleRollover(){ if(!state||!state.currentCycle||!state.currentCycle.endDate) return; let now=new Date(); let end=new Date(state.currentCycle.endDate); while(now>=end){ const leftover=getSalaryBalance(); if(leftover>0) state.extra.balance=roundMoney(state.extra.balance+leftover); state.cycles.push(JSON.parse(JSON.stringify(state.currentCycle))); const cycleDay=state.settings.cycleDay||5; const newStart=new Date(end); const newEnd=new Date(newStart.getFullYear(),newStart.getMonth()+1,cycleDay); state.currentCycle={id:createId(),startDate:newStart.toISOString(),endDate:newEnd.toISOString(),salaryReceived:roundMoney(state.salary.reference),leftoverSalary:0,expenses:[],transfers:[],categoryUsage:{}}; normalizeCycle(state.currentCycle); end=new Date(state.currentCycle.endDate); } saveState(); }
function startInitialSetup(){ state=createEmptyState(); setupCategories=DEFAULT_CATEGORIES.map(c=>({...c})); currentSetupStep=1; setupSalarySplit=null; showScreen("setup",false); renderSetupStep(); }
function renderSetupStep(){ document.querySelectorAll(".setup-step").forEach(s=>{ const n=Number(s.dataset.step); s.classList.toggle("hidden",n!==currentSetupStep); }); if(currentSetupStep===7) renderSetupCategories(); const btn=$("setup-next-button"); if(btn) btn.textContent=currentSetupStep===7?"Concluir":"Continuar"; if(state?.user?.displayName) setText("setup-greeting-preview",`Olá, ${state.user.displayName}`); }
function renderSetupCategories(){ const c=$("setup-categories"); if(!c) return; c.innerHTML=""; setupCategories.forEach((cat,idx)=>{ const item=document.createElement("div"); item.className="settings-category-item"; item.style.cssText="display:flex;justify-content:space-between;align-items:center;padding:10px;background:var(--surface-2);border:1px solid var(--border);border-radius:10px;margin-bottom:8px;cursor:pointer"; item.setAttribute("data-setup-cat-index",idx); const isBlocked=cat.id==="reserve"||cat.id==="other"; const limitLabel=isBlocked?"Sem limite (fixo)":(cat.hasLimit&&cat.limit?`Limite: ${formatMoney(cat.limit)}`:"Sem limite (Toque para ajustar)"); item.innerHTML=`<div style="display:flex;align-items:center;gap:10px"><div style="color:var(--accent)">${getCategoryIconSvg(cat)}</div><div><div>${escapeHTML(cat.name)}</div><div style="font-size:12px;color:${isBlocked?'var(--text-muted)':'var(--accent)'}">${limitLabel}</div></div></div>${!isBlocked?'<span style="font-size:12px">Editar</span>':''}`; c.appendChild(item); }); }
function openSetupLimitModal(i){ const cat=setupCategories[i]; if(!cat) return; if(cat.id==="reserve"||cat.id==="other"){ customAlert("Reserva e Outros sem limite."); return; } editingSetupCategoryIndex=i; $("setup-limit-title").textContent=`Limite: ${cat.name}`; setupLimitHasLimit=!!cat.hasLimit; $("setup-limit-val").value=cat.limit?cat.limit.toFixed(2):""; updateSetupLimitButtons(); openModal("setup-limit-modal"); }
function updateSetupLimitButtons(){ $("setup-limit-yes")?.classList.toggle("selected",setupLimitHasLimit); $("setup-limit-no")?.classList.toggle("selected",!setupLimitHasLimit); $("setup-limit-input-container")?.classList.toggle("hidden",!setupLimitHasLimit); }
function saveSetupLimit(){ if(editingSetupCategoryIndex===null) return; const cat=setupCategories[editingSetupCategoryIndex]; if(!cat) return; if(setupLimitHasLimit){ const v=parseMoneyInput($("setup-limit-val").value); if(v<=0) return customAlert("Valor inválido."); cat.hasLimit=true; cat.limit=v; } else { cat.hasLimit=false; cat.limit=null; } closeModal("setup-limit-modal"); renderSetupCategories(); }
async function handleSetupNext(){
  if(currentSetupStep===1){
    const user=$("setup-username")?.value.trim(); const pass=$("setup-password")?.value; const repeat=$("setup-repeat-password")?.value;
    if(!user) return customAlert("Digite seu usuário."); if(!pass) return customAlert("Crie uma senha."); if(pass.length<4) return customAlert("Senha mínima 4 caracteres."); if(pass!==repeat) return customAlert("Senhas não coincidem.");
    state.user.username=user; state.security.passwordHash=await hashPassword(pass); localStorage.setItem("fx_temp_key", state.security.passwordHash.slice(0,16));
  }
  if(currentSetupStep===2){
    const full=$("setup-fullname")?.value.trim(); const display=$("setup-displayname")?.value.trim();
    if(!full) return customAlert("Digite nome completo."); state.user.fullName=full; state.user.displayName=display||full.split(" ")[0];
  }
  if(currentSetupStep===3){
    const q=$("setup-security-question")?.value.trim(); const a=$("setup-security-answer")?.value.trim();
    if(!q||!a) return customAlert("Preencha pergunta e resposta."); state.security.recoveryQuestion=q; state.security.recoveryAnswerHash=await hashPassword(a.toLowerCase());
  }
  if(currentSetupStep===4){ const v=parseMoneyInput($("setup-salary")?.value); if(v<=0) return customAlert("Salário deve ser maior que zero."); state.salary.reference=v; }
  if(currentSetupStep===5){ if(!setupSalarySplit) return customAlert("Escolha uma opção."); state.salary.hasAdvance=setupSalarySplit==="yes"; state.salary.advanceAmount=state.salary.hasAdvance?parseMoneyInput($("setup-advance-val")?.value):0; }
  if(currentSetupStep===6){ const day=Number($("setup-cycle-day")?.value); if(!Number.isInteger(day)||day<1||day>28) return customAlert("Dia entre 1 e 28."); state.settings.cycleDay=day; }
  if(currentSetupStep<7){ currentSetupStep++; renderSetupStep(); return; }
  completeInitialSetup();
}
function completeInitialSetup(){ state.categories=setupCategories.map(c=>({...c})); state.setupCompleted=true; state.security.locked=false; createInitialCycle(); saveState(); localStorage.removeItem("fx_temp_key"); showScreen("main",false); renderApplication(); }
function createInitialCycle(){ const now=new Date(); const start=new Date(now.getFullYear(),now.getMonth(),state.settings.cycleDay); const end=new Date(now.getFullYear(),now.getMonth()+1,state.settings.cycleDay); state.currentCycle={id:createId(),startDate:start.toISOString(),endDate:end.toISOString(),salaryReceived:roundMoney(state.salary.reference),leftoverSalary:0,expenses:[],transfers:[],categoryUsage:{}}; normalizeCycle(state.currentCycle); }
function getSalaryBalance(){ if(!state||!state.currentCycle) return 0; let b=Number(state.currentCycle.salaryReceived)||0; state.currentCycle.expenses.forEach(e=>{ if(e.origin==="salary") b-=Number(e.amount)||0; }); state.currentCycle.transfers.forEach(t=>{ if(t.origin==="salary") b-=Number(t.amount)||0; }); return roundMoney(Math.max(0,b)); }
function getExtraBalance(){ return roundMoney(Math.max(0,Number(state.extra?.balance)||0)); }
function getReserveBalance(){ return roundMoney(Math.max(0,Number(state.reserve?.balance)||0)); }
function launchExpense(catId,amount,origin,desc){ if(catId==="reserve"){ openReserveModal(); return; } amount=roundMoney(amount); if(amount<=0) throw new Error("Valor deve ser maior que zero."); const cat=state.categories.find(c=>c.id===catId); if(cat&&cat.hasLimit&&cat.limit>0){ const usage=state.currentCycle.categoryUsage[catId]||0; if(roundMoney(usage+amount)>cat.limit) throw new Error(`Excede limite ${formatMoney(cat.limit)}`); } const available=origin==="salary"?getSalaryBalance():getExtraBalance(); if(amount>available) throw new Error("Saldo insuficiente."); if(origin==="extra") state.extra.balance=roundMoney(state.extra.balance-amount); const expense={id:createId(),origin,amount,description:desc||"",categoryId:catId,date:new Date().toISOString()}; state.currentCycle.expenses.push(expense); normalizeCycle(state.currentCycle); saveState(); if(document.activeElement) document.activeElement.blur(); renderApplication(); }
function openEditExpenseModal(expenseId){ const expense=state.currentCycle.expenses.find(e=>e.id===expenseId); if(!expense) return; currentEditingExpenseId=expenseId; $("edit-expense-value").value=expense.amount.toFixed(2); $("edit-expense-description").value=expense.description||""; selectedEditExpenseOrigin=expense.origin; selectedEditExpenseCategory=expense.categoryId; updateCustomSelectTriggers(); hideElement("edit-expense-error"); openModal("expense-edit-modal"); }
function saveExpenseEdit(){ try{ const expense=state.currentCycle.expenses.find(e=>e.id===currentEditingExpenseId); if(!expense) throw new Error("Gasto não encontrado."); const newAmount=parseMoneyInput($("edit-expense-value").value); const newOrigin=selectedEditExpenseOrigin; const newCategory=selectedEditExpenseCategory; const newDesc=$("edit-expense-description").value.trim(); if(newAmount<=0) throw new Error("Valor > zero."); const target=state.categories.find(c=>c.id===newCategory); if(target&&target.hasLimit&&target.limit>0){ let usage=state.currentCycle.categoryUsage[newCategory]||0; if(expense.categoryId===newCategory) usage-=expense.amount; if(roundMoney(usage+newAmount)>target.limit) throw new Error(`Excede limite ${formatMoney(target.limit)}`); } const oldAmount=expense.amount; const oldOrigin=expense.origin; if(oldOrigin==="extra") state.extra.balance=roundMoney(state.extra.balance+oldAmount); if(oldOrigin==="reserve") state.reserve.balance=roundMoney(state.reserve.balance+oldAmount); if(newOrigin==="extra"){ if(newAmount>getExtraBalance()){ if(oldOrigin==="extra") state.extra.balance=roundMoney(state.extra.balance-oldAmount); if(oldOrigin==="reserve") state.reserve.balance=roundMoney(state.reserve.balance-oldAmount); throw new Error("Saldo insuficiente Extra."); } state.extra.balance=roundMoney(state.extra.balance-newAmount); } else if(newOrigin==="reserve"){ if(newAmount>getReserveBalance()){ if(oldOrigin==="extra") state.extra.balance=roundMoney(state.extra.balance-oldAmount); if(oldOrigin==="reserve") state.reserve.balance=roundMoney(state.reserve.balance-oldAmount); throw new Error("Saldo insuficiente Reserva."); } state.reserve.balance=roundMoney(state.reserve.balance-newAmount); } else if(newOrigin==="salary"){ expense.amount=0; if(newAmount>getSalaryBalance()){ expense.amount=oldAmount; if(oldOrigin==="extra") state.extra.balance=roundMoney(state.extra.balance-oldAmount); if(oldOrigin==="reserve") state.reserve.balance=roundMoney(state.reserve.balance-oldAmount); throw new Error("Saldo insuficiente Salário."); } } expense.amount=newAmount; expense.origin=newOrigin; expense.categoryId=newCategory; expense.description=newDesc; normalizeCycle(state.currentCycle); saveState(); closeModal("expense-edit-modal"); currentEditingExpenseId=null; if(document.activeElement) document.activeElement.blur(); renderApplication(); }catch(err){ showElement("edit-expense-error",err.message); } }
function deleteExpense(){ if(!currentEditingExpenseId) return; customConfirm("Excluir este gasto?",()=>{ const idx=state.currentCycle.expenses.findIndex(e=>e.id===currentEditingExpenseId); if(idx===-1) return; const exp=state.currentCycle.expenses[idx]; if(exp.origin==="extra") state.extra.balance=roundMoney(state.extra.balance+exp.amount); if(exp.origin==="reserve") state.reserve.balance=roundMoney(state.reserve.balance+exp.amount); state.currentCycle.expenses.splice(idx,1); normalizeCycle(state.currentCycle); saveState(); closeModal("expense-edit-modal"); currentEditingExpenseId=null; if(document.activeElement) document.activeElement.blur(); renderApplication(); }); }
function openCategoryDetails(catId){ const cat=state.categories.find(c=>c.id===catId); if(!cat) return; if(cat.id==="reserve"){ openReserveModal(); return; } const container=$("category-details"); if(!container) return; const expenses=(state.currentCycle?.expenses||[]).filter(e=>e.categoryId===catId).sort((a,b)=>new Date(b.date)-new Date(a.date)); const usage=state.currentCycle.categoryUsage[catId]||0; let html=`<div style="text-align:center;padding-bottom:12px"><div style="display:inline-flex;align-items:center;justify-content:center;width:48px;height:48px;border-radius:50%;background:var(--surface-3);color:var(--accent);margin-bottom:8px">${getCategoryIconSvg(cat)}</div><h3 style="font-size:20px;font-weight:800">${escapeHTML(cat.name)}</h3><p style="color:var(--text-secondary);font-size:14px;margin-top:4px">Total: <strong>${formatMoneyOrMask(usage)}</strong></p></div><div class="expense-group-items">`; if(!expenses.length){ html+=`<div style="padding:20px;text-align:center;color:var(--text-muted)">Nenhum gasto.</div>`; } else { expenses.forEach(exp=>{ html+=`<div class="expense-item-card" data-edit-expense-id="${exp.id}"><div class="expense-item-left"><div class="expense-item-details"><span class="expense-item-title">${escapeHTML(exp.description||cat.name)}</span><span class="expense-item-time">${new Date(exp.date).toLocaleDateString("pt-BR")}</span></div></div><span class="expense-item-amount">${formatMoneyOrMask(exp.amount)}</span></div>`; }); } html+=`</div>`; container.innerHTML=html; openModal("category-modal"); }
function openHistoryModal(cycleId=null){ const container=$("history-container"); if(!container) return; if(!state.cycles||!state.cycles.length){ container.innerHTML=`<div style="text-align:center;padding:20px;color:var(--text-muted)">Nenhum histórico.</div>`; openModal("history-modal"); return; } if(cycleId){ const cycle=state.cycles.find(c=>c.id===cycleId); if(!cycle) return; const startStr=new Date(cycle.startDate).toLocaleDateString("pt-BR"); const endStr=new Date(cycle.endDate).toLocaleDateString("pt-BR"); const total=(cycle.expenses||[]).reduce((a,e)=>a+(Number(e.amount)||0),0); let expHtml=""; if(!cycle.expenses||!cycle.expenses.length){ expHtml=`<div style="padding:15px;text-align:center;color:var(--text-muted)">Nenhum gasto.</div>`; } else { cycle.expenses.forEach(exp=>{ const cat=state.categories.find(c=>c.id===exp.categoryId); const catName=cat?cat.name:"Outros"; expHtml+=`<div class="expense-item-card" style="cursor:default"><div class="expense-item-left"><div class="expense-item-details"><span class="expense-item-title">${escapeHTML(exp.description||catName)}</span><div class="expense-item-sub"><span class="expense-origin-badge badge-reserve">${exp.origin}</span><span class="expense-item-time">${new Date(exp.date).toLocaleDateString("pt-BR")}</span></div></div></div><span class="expense-item-amount">${formatMoneyOrMask(exp.amount)}</span></div>`; }); } container.innerHTML=`<button type="button" class="secondary-button" style="margin-bottom:12px;min-height:36px" data-back-to-history="true">← Voltar</button><div style="font-weight:700;font-size:16px;color:var(--accent);margin-bottom:4px">Ciclo (${startStr} até ${endStr})</div><p style="font-size:13px;color:var(--text-secondary);margin-bottom:12px">Total: <strong>${formatMoneyOrMask(total)}</strong></p><div class="expense-group-items">${expHtml}</div>`; openModal("history-modal"); return; } let html=`<div style="display:flex;flex-direction:column;gap:12px">`; state.cycles.slice().reverse().forEach((cycle,idx)=>{ const s=new Date(cycle.startDate).toLocaleDateString("pt-BR"); const e=new Date(cycle.endDate).toLocaleDateString("pt-BR"); const tot=(cycle.expenses||[]).reduce((a,x)=>a+(Number(x.amount)||0),0); html+=`<div style="padding:14px;background:var(--surface-2);border:1px solid var(--border);border-radius:var(--radius-small);cursor:pointer" data-history-cycle-id="${cycle.id}"><div style="font-weight:700;font-size:14px;color:var(--accent)">Ciclo ${state.cycles.length-idx} (${s} até ${e})</div><div style="display:flex;justify-content:space-between;margin-top:6px;font-size:13px;color:var(--text-secondary)"><span>Total:</span><strong style="color:var(--text)">${formatMoneyOrMask(tot)}</strong></div></div>`; }); html+=`</div>`; container.innerHTML=html; openModal("history-modal"); }
function openReserveModal(){ if($("reserve-value")) $("reserve-value").value=""; if($("withdraw-value")) $("withdraw-value").value=""; selectedReserveOrigin="salary"; hideElement("reserve-error"); hideElement("reserve-form"); hideElement("withdraw-form"); hideElement("reserve-origin-section"); updateReserveModalOriginButtons(); setText("reserve-balance",formatMoneyOrMask(getReserveBalance())); openModal("reserve-modal"); }
function updateReserveModalOriginButtons(){ const s=$("reserve-origin-salary-btn"); const ex=$("reserve-origin-extra-btn"); if(s) s.classList.toggle("selected",selectedReserveOrigin==="salary"); if(ex) ex.classList.toggle("selected",selectedReserveOrigin==="extra"); setText("reserve-salary-available",formatMoneyOrMask(getSalaryBalance())); setText("reserve-extra-available",formatMoneyOrMask(getExtraBalance())); }
function showReserveSaveForm(){ hideElement("withdraw-form"); showElement("reserve-form"); showElement("reserve-origin-section"); updateReserveModalOriginButtons(); }
function showWithdrawForm(){ hideElement("reserve-form"); hideElement("reserve-origin-section"); showElement("withdraw-form"); }
function confirmReserveSave(){ try{ if(!selectedReserveOrigin) throw new Error("Selecione origem."); const amount=parseMoneyInput($("reserve-value")?.value); if(amount<=0) throw new Error("Valor > zero."); const available=selectedReserveOrigin==="salary"?getSalaryBalance():getExtraBalance(); if(amount>available) throw new Error("Saldo insuficiente."); if(selectedReserveOrigin==="extra") state.extra.balance=roundMoney(state.extra.balance-amount); state.currentCycle.transfers.push({id:createId(),origin:selectedReserveOrigin,amount,date:new Date().toISOString()}); state.reserve.balance=roundMoney(state.reserve.balance+amount); saveState(); closeModal("reserve-modal"); if(document.activeElement) document.activeElement.blur(); renderApplication(); }catch(err){ showElement("reserve-error",err.message); } }
function confirmReserveWithdraw(){ try{ const amount=parseMoneyInput($("withdraw-value")?.value); if(amount<=0) throw new Error("Valor > zero."); if(amount>getReserveBalance()) throw new Error("Saldo insuficiente Reserva."); state.reserve.balance=roundMoney(state.reserve.balance-amount); const expense={id:createId(),origin:"reserve",amount,description:"Retirada da Reserva",categoryId:"other",date:new Date().toISOString()}; state.currentCycle.expenses.push(expense); normalizeCycle(state.currentCycle); saveState(); closeModal("reserve-modal"); if(document.activeElement) document.activeElement.blur(); renderApplication(); }catch(err){ showElement("reserve-error",err.message); } }
async function exportBackup(){ try{ const password=prompt("Crie senha para backup:"); if(!password) return customAlert("Cancelado."); const json=JSON.stringify(state); const enc=await encryptData(json,password); const payload=JSON.stringify({fx_encrypted:true,version:FX_VERSION,payload:enc},null,2); const dateStr=new Date().toISOString().slice(0,10); const blob=new Blob([payload],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`fx_backup_${dateStr}.json`; a.click(); URL.revokeObjectURL(url); }catch(err){ customAlert("Erro export: "+err.message); } }
async function exportCSV(){ try{ const expenses=state.currentCycle?.expenses||[]; if(!expenses.length) return customAlert("Sem lançamentos."); let csv="\uFEFFData;Categoria;Origem;Descrição;Valor\n"; expenses.forEach(exp=>{ const cat=state.categories.find(c=>c.id===exp.categoryId); const catName=cat?cat.name:"Outros"; const dateStr=new Date(exp.date).toLocaleDateString("pt-BR"); const origin=exp.origin==="salary"?"Salário":exp.origin==="extra"?"Extra":"Reserva"; const desc=(exp.description||catName).replace(/;/g,","); const val=exp.amount.toFixed(2).replace(".",","); csv+=`${dateStr};"${catName}";${origin};"${desc}";${val}\n`; }); const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`fx_extrato_${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); }catch(err){ customAlert("Erro CSV: "+err.message); } }
function importBackup(e){ const file=e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=async function(ev){ try{ const raw=JSON.parse(ev.target.result); let imported=null; if(raw&&raw.fx_encrypted&&raw.payload){ const pw=prompt("Senha do backup:"); if(!pw) return customAlert("Cancelado."); try{ const dec=await decryptData(raw.payload,pw); imported=JSON.parse(dec);}catch{ throw new Error("Senha incorreta ou corrompido."); } } else { imported=raw; } validateBackupSchema(imported); state=imported; normalizeState(); await saveState(); renderApplication(); customAlert("Importado com sucesso!"); }catch(err){ customAlert("Erro import: "+err.message); } finally{ e.target.value=""; } }; reader.readAsText(file); }
async function checkBiometricSupport(){ if(window.Capacitor?.Plugins?.NativeBiometric){ try{ const r=await window.Capacitor.Plugins.NativeBiometric.isAvailable(); return {type:"capacitor",available:!!r.isAvailable}; }catch{ return {type:"none",available:false}; } } if(window.PublicKeyCredential && (location.protocol==="https:"||location.hostname==="localhost")){ try{ const av=await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable(); return {type:"webauthn",available:!!av}; }catch{ return {type:"none",available:false}; } } return {type:"none",available:false}; }
async function registerBiometrics(){ const sup=await checkBiometricSupport(); if(!sup.available) return customAlert("Biometria não disponível."); if(sup.type==="capacitor"){ try{ await window.Capacitor.Plugins.NativeBiometric.verifyIdentity({reason:"Cadastrar biometria FX",title:"Biometria FX",subtitle:"Confirme"}); state.security.biometricId="native_capacitor"; state.security.biometricType="capacitor"; await saveState(); customAlert("Biometria cadastrada!"); }catch(err){ customAlert("Não foi possível: "+(err.message||"Cancelado")); } } }
async function authenticateBiometric(){ if(!state?.security?.biometricId) return; const sup=await checkBiometricSupport(); if(!sup.available){ showElement("unlock-error","Biometria desativada no sistema. Use senha."); return; } if(sup.type==="capacitor"){ try{ await window.Capacitor.Plugins.NativeBiometric.verifyIdentity({reason:"Acesse FX",title:"Desbloqueio FX",subtitle:"Confirme"}); unlockSuccess(); }catch{ showElement("unlock-error","Biometria não reconhecida. Use senha."); } } }
function unlockSuccess(){ state.security.locked=false; saveState(); showScreen("main",false); renderApplication(); }
function openForgotPasswordModal(){ if(!state.security.recoveryQuestion) return customAlert("Pergunta não configurada."); setText("recovery-question-display",state.security.recoveryQuestion); if($("recovery-answer-input")) $("recovery-answer-input").value=""; if($("recovery-new-password")) $("recovery-new-password").value=""; hideElement("recovery-error"); openModal("forgot-password-modal"); }
async function confirmPasswordRecovery(){ const ans=$("recovery-answer-input")?.value.trim().toLowerCase(); const newPass=$("recovery-new-password")?.value; if(!ans) return showElement("recovery-error","Digite resposta."); if(!newPass) return showElement("recovery-error","Digite nova senha."); const h=await hashPassword(ans); if(h!==state.security.recoveryAnswerHash) return showElement("recovery-error","Resposta incorreta."); state.security.passwordHash=await hashPassword(newPass); localStorage.setItem("fx_temp_key",state.security.passwordHash.slice(0,16)); state.security.locked=false; await saveState(); closeModal("forgot-password-modal"); customAlert("Senha redefinida!"); showScreen("main",false); renderApplication(); }
function openRecoveryQuestionSetupModal(){ if($("setup-sec-q-input")) $("setup-sec-q-input").value=state.security.recoveryQuestion||""; if($("setup-sec-a-input")) $("setup-sec-a-input").value=""; hideElement("sec-q-error"); openModal("recovery-question-setup-modal"); }
async function saveRecoveryQuestionSetup(){ const q=$("setup-sec-q-input")?.value.trim(); const a=$("setup-sec-a-input")?.value.trim().toLowerCase(); if(!q||!a) return showElement("sec-q-error","Preencha tudo."); state.security.recoveryQuestion=q; state.security.recoveryAnswerHash=await hashPassword(a); await saveState(); closeModal("recovery-question-setup-modal"); customAlert("Pergunta atualizada!"); renderApplication(); }
function updateCustomSelectTriggers(){ const o=$("edit-expense-origin-trigger"); if(o){ if(selectedEditExpenseOrigin==="salary") o.textContent="Salário"; else if(selectedEditExpenseOrigin==="extra") o.textContent="Extra"; else o.textContent="Reserva"; } const c=$("edit-expense-category-trigger"); if(c){ const cat=state.categories.find(x=>x.id===selectedEditExpenseCategory); c.textContent=cat?cat.name:"Selecione"; } const ic=$("category-icon-trigger"); if(ic){ const labels={fixed:"Gasto Fixo (Casa)",reserve:"Reserva (Cofre)",medicine:"Medicamentos (Remédio)",leisure:"Lazer (Controle)",phone:"Telefone / Internet",other:"Outros (Caixa)"}; ic.textContent=labels[selectedCategoryIcon]||"Outros"; } }
function openCustomPicker(title,opts,onSelect){ $("picker-title").textContent=title; const cont=$("picker-options"); cont.innerHTML=""; opts.forEach(opt=>{ const b=document.createElement("button"); b.type="button"; b.className="picker-option-button"; b.style.cssText="width:100%;padding:12px;background:var(--surface-2);border:1px solid var(--border);border-radius:10px;margin-bottom:8px;display:flex;justify-content:space-between"; b.innerHTML=`<span>${escapeHTML(opt.label)}</span>${opt.selected?'<span style="color:var(--accent)">✓</span>':''}`; b.onclick=()=>{ onSelect(opt.value); closeModal("picker-modal"); updateCustomSelectTriggers(); }; cont.appendChild(b); }); openModal("picker-modal"); }
function renderSettingsCategories(){ const cont=$("settings-categories-list"); if(!cont) return; cont.innerHTML=""; const frag=document.createDocumentFragment(); state.categories.forEach(cat=>{ const item=document.createElement("div"); item.className="settings-category-item"; item.style.cssText="display:flex;justify-content:space-between;align-items:center;padding:10px;background:var(--surface-2);border:1px solid var(--border);border-radius:10px;margin-bottom:8px"; item.innerHTML=`<div style="display:flex;align-items:center;gap:10px"><div style="color:var(--accent)">${getCategoryIconSvg(cat)}</div><div><div>${escapeHTML(cat.name)}</div><div style="font-size:12px;color:var(--text-secondary)">${cat.hasLimit&&cat.limit?`Limite: ${formatMoneyOrMask(cat.limit)}`:"Sem limite"}</div></div></div><button type="button" class="secondary-button" style="width:auto;padding:6px 14px;min-height:34px;font-size:12px" data-edit-category-id="${cat.id}">Editar</button>`; frag.appendChild(item); }); cont.appendChild(frag); }
function openCategoryEditorModal(catId=null){ if(catId==="reserve"||catId==="other"){ customAlert("Reserva e Outros não editam limite."); return; } currentEditingCategoryId=catId; hideElement("category-editor-error"); if(catId){ const cat=state.categories.find(c=>c.id===catId); if(!cat) return; if($("category-editor-title")) $("category-editor-title").textContent="Editar Categoria"; $("category-name").value=cat.name; selectedCategoryIcon=cat.icon||"other"; categoryEditorHasLimit=!!cat.hasLimit; $("category-limit-value").value=cat.limit?cat.limit.toFixed(2):""; } else { if($("category-editor-title")) $("category-editor-title").textContent="Criar Categoria"; $("category-name").value=""; selectedCategoryIcon="other"; categoryEditorHasLimit=false; $("category-limit-value").value=""; } document.querySelectorAll("[data-category-limit]").forEach(b=>b.classList.toggle("selected",b.dataset.categoryLimit===(categoryEditorHasLimit?"yes":"no"))); $("category-limit-value-container")?.classList.toggle("hidden",!categoryEditorHasLimit); updateCustomSelectTriggers(); openModal("category-editor-modal"); }
function saveCategory(){ try{ const name=$("category-name").value.trim(); const icon=selectedCategoryIcon||"other"; const limitVal=parseMoneyInput($("category-limit-value").value); if(!name) throw new Error("Digite nome."); if(state.categories.some(c=>c.name.toLowerCase()===name.toLowerCase()&&c.id!==currentEditingCategoryId)) throw new Error("Categoria já existe."); if(categoryEditorHasLimit&&limitVal<=0) throw new Error("Limite inválido."); if(currentEditingCategoryId){ const cat=state.categories.find(c=>c.id===currentEditingCategoryId); if(cat){ cat.name=name; cat.icon=icon; cat.hasLimit=categoryEditorHasLimit; cat.limit=categoryEditorHasLimit?limitVal:null; } } else { state.categories.push({id:createId(),name,icon,hasLimit:categoryEditorHasLimit,limit:categoryEditorHasLimit?limitVal:null,protected:false}); } normalizeCycle(state.currentCycle); saveState(); closeModal("category-editor-modal"); if(document.activeElement) document.activeElement.blur(); renderApplication(); }catch(err){ showElement("category-editor-error",err.message); } }
function openChartModal(){ const cont=$("chart-container"); if(!cont) return; const totals=state.categories.map(c=>({name:c.name,icon:getCategoryIconSvg(c),value:state.currentCycle.categoryUsage[c.id]||0})).filter(c=>c.value>0); const sum=totals.reduce((a,c)=>a+c.value,0); if(!totals.length||sum<=0) return customAlert("Sem gastos."); let cursor=0; const segs=totals.map((item,idx)=>{ const pct=(item.value/sum)*100; const s=cursor; cursor+=pct; const hue=Math.round((idx/totals.length)*360); return {...item,pct,start:s,end:cursor,color:`hsl(${hue} 70% 50%)`}; }); const grad=segs.map(s=>`${s.color} ${s.start}% ${s.end}%`).join(", "); const legend=segs.map(s=>`<div class="pizza-legend-item"><span style="display:flex;align-items:center;gap:8px"><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${s.color}"></span>${escapeHTML(s.name)}</span><strong>${formatMoneyOrMask(s.value)} (${s.pct.toFixed(1)}%)</strong></div>`).join(""); cont.innerHTML=`<div class="pizza-chart" style="background: conic-gradient(${grad}); position:relative; margin:0 auto"><div style="position:absolute;inset:25%;background:var(--surface);border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:800">${formatMoneyOrMask(sum)}</div></div><div class="pizza-legend">${legend}</div>`; openModal("chart-modal"); }
function saveProfileSettings(){ const full=$("settings-fullname")?.value.trim(); const display=$("settings-displayname")?.value.trim(); if(!full) return customAlert("Digite nome completo."); state.user.fullName=full; state.user.displayName=display||full.split(" ")[0]; saveState(); renderApplication(); customAlert("Salvo."); }
function saveSalarySettings(){ const salary=parseMoneyInput($("settings-salary")?.value); if(salary<0) return customAlert("Salário não pode ser negativo."); state.salary.reference=salary; state.salary.hasAdvance=settingsSalarySplit==="yes"; state.salary.advanceAmount=state.salary.hasAdvance?parseMoneyInput($("settings-advance-val")?.value):0; if(state.currentCycle) state.currentCycle.salaryReceived=roundMoney(salary); saveState(); renderApplication(); customAlert("Salário salvo."); }
function saveCycleSettings(){ const newDay=Number($("settings-cycle-day")?.value); if(!Number.isInteger(newDay)||newDay<1||newDay>28) return customAlert("Dia 1-28."); state.settings.cycleDay=newDay; saveState(); renderApplication(); customAlert("Aplicado próximo ciclo."); }
async function saveNewPassword(){ const cur=$("current-password")?.value; const np=$("new-password")?.value; const cp=$("confirm-new-password")?.value; const curHash=await hashPassword(cur); if(curHash!==state.security.passwordHash) return showElement("password-error","Senha atual incorreta."); if(!np) return showElement("password-error","Digite nova."); if(np!==cp) return showElement("password-error","Não coincidem."); state.security.passwordHash=await hashPassword(np); localStorage.setItem("fx_temp_key",state.security.passwordHash.slice(0,16)); await saveState(); closeModal("password-modal"); customAlert("Senha alterada."); }
async function deleteAllData(){ const pass=$("delete-password")?.value; const conf=$("delete-confirmation")?.value.trim(); const ph=await hashPassword(pass); if(ph!==state.security.passwordHash) return showElement("delete-error","Senha incorreta."); if(conf!=="APAGAR") return showElement("delete-error","Digite APAGAR."); localStorage.removeItem(STORAGE_KEY); localStorage.removeItem("fx_temp_key"); state=null; closeModal("delete-data-modal"); startInitialSetup(); }
function lockApp(){ if(state) state.security.locked=true; if($("unlock-password")){ $("unlock-password").value=""; $("unlock-password").type="password"; } renderLockPasswordIcon(); hideElement("unlock-error"); const initial=(state&&state.user&&state.user.displayName)?state.user.displayName.charAt(0).toUpperCase():"FX"; setText("lock-avatar",initial); setText("lock-user-greeting",`Olá, ${state?.user?.displayName||state?.user?.username||"Titular"}`); const bio=$("biometric-unlock-icon"); if(state&&state.security&&state.security.biometricId){ if(bio) bio.classList.remove("hidden"); saveState(); showScreen("lock",false); setTimeout(()=>{ authenticateBiometric(); },300); } else { if(bio) bio.classList.add("hidden"); saveState(); showScreen("lock",false); } }
function renderLockPasswordIcon(){ const c=$("eye-icon-container"); if(!c) return; const isText=$("unlock-password")?.type==="text"; c.innerHTML=isText?SVG_EYE_SLASH:SVG_EYE_OPEN; }
function renderHideBalancesIcon(){ const c=$("hide-balances-icon-container"); if(!c) return; c.innerHTML=state.settings.hideBalances?SVG_EYE_SLASH:SVG_EYE_OPEN; }
function toggleHideBalances(){ if(!state) return; state.settings.hideBalances=!state.settings.hideBalances; saveState(); renderApplication(); }
function customAlert(msg){ setText("custom-alert-message",msg); openModal("custom-alert-modal"); }
function customConfirm(msg,cb){ setText("custom-confirm-message",msg); customConfirmCallback=cb; openModal("custom-confirm-modal"); }
function renderPersonalization(){ const ap=localStorage.getItem("fx_appearance")||"dark"; const th=localStorage.getItem("fx_theme")||"theme1"; document.querySelectorAll("[data-appearance-choice]").forEach(b=>b.classList.toggle("selected",b.dataset.appearanceChoice===ap)); document.querySelectorAll("[data-theme-choice]").forEach(b=>b.classList.toggle("selected",b.dataset.themeChoice===th)); }
function renderApplication(){ if(!state) return; setText("user-display-name",state.user?.displayName||state.user?.username||"Titular"); renderHideBalancesIcon(); renderBalances(); renderCategories(); renderExpensesGrouped(); renderSettingsCategories(); renderSettingsValues(); renderPersonalization(); }
function renderBalances(){ const salary=getSalaryBalance(); const extra=getExtraBalance(); const available=roundMoney(salary+extra); setText("salary-balance",formatMoneyOrMask(salary)); setText("extra-balance",formatMoneyOrMask(extra)); setText("available-balance",formatMoneyOrMask(available)); setText("reserve-balance",formatMoneyOrMask(getReserveBalance())); }
function renderCategories(){ const cont=$("categories-list"); if(!cont) return; cont.innerHTML=""; const frag=document.createDocumentFragment(); state.categories.forEach(cat=>{ const card=document.createElement("div"); card.className="category-card"; const usage=state.currentCycle?.categoryUsage[cat.id]||0; let spent=""; let prog=""; if(cat.id==="reserve"){ spent=`Saldo: ${formatMoneyOrMask(getReserveBalance())}`; } else if(cat.hasLimit&&cat.limit>0){ const pct=Math.min(100,(usage/cat.limit)*100); const full=usage>=cat.limit; spent=`${formatMoneyOrMask(usage)} / ${formatMoneyOrMask(cat.limit)}`; prog=`<div class="category-progress"><div class="category-progress-bar ${full?"full":""}" style="width:${pct}%"></div></div>`; } else { spent=`Consumido: ${formatMoneyOrMask(usage)}`; } card.innerHTML=`<div class="category-main" data-category-expense="${cat.id}"><div class="category-top"><span class="category-name" style="display:flex;align-items:center;gap:8px">${getCategoryIconSvg(cat)}${escapeHTML(cat.name)}</span><span class="category-balance">${spent}</span></div>${prog}</div><button type="button" class="category-icon-button" data-category-open="${cat.id}" aria-label="Detalhes">⋮</button>`; frag.appendChild(card); }); cont.appendChild(frag); }
function renderExpensesGrouped(){ const cont=$("expenses-list"); if(!cont) return; cont.innerHTML=""; const expenses=state.currentCycle?.expenses||[]; if(!expenses.length){ cont.innerHTML=`<div style="text-align:center;padding:30px;color:var(--text-muted)">Nenhum gasto neste ciclo.</div>`; return; } const groups={}; expenses.forEach(exp=>{ const key=new Date(exp.date).toLocaleDateString("pt-BR",{day:"2-digit",month:"long"}); if(!groups[key]) groups[key]=[]; groups[key].push(exp); }); const frag=document.createDocumentFragment(); Object.keys(groups).forEach(dateTitle=>{ const g=document.createElement("div"); g.className="expense-group"; let items=""; groups[dateTitle].forEach(exp=>{ const cat=state.categories.find(c=>c.id===exp.categoryId); const catName=cat?cat.name:"Outros"; let badge="badge-extra",label="Extra"; if(exp.origin==="salary"){ badge="badge-salary"; label="Salário"; } else if(exp.origin==="reserve"){ badge="badge-reserve"; label="Reserva"; } items+=`<div class="expense-item-card" data-edit-expense-id="${exp.id}"><div class="expense-item-left"><div class="expense-item-icon" style="color:var(--accent)">${getCategoryIconSvg(cat)}</div><div class="expense-item-details"><span class="expense-item-title">${escapeHTML(exp.description||catName)}</span><div class="expense-item-sub"><span class="expense-origin-badge ${badge}">${label}</span><span class="expense-item-time">${new Date(exp.date).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></div></div></div><span class="expense-item-amount">${formatMoneyOrMask(exp.amount)}</span></div>`; }); g.innerHTML=`<div class="expense-group-date">${dateTitle}</div><div class="expense-group-items">${items}</div>`; frag.appendChild(g); }); cont.appendChild(frag); }
function renderSettingsValues(){ if($("settings-fullname")) $("settings-fullname").value=state.user?.fullName||""; if($("settings-displayname")) $("settings-displayname").value=state.user?.displayName||""; if($("settings-salary")) $("settings-salary").value=Number(state.salary.reference).toFixed(2); if($("settings-cycle-day")) $("settings-cycle-day").value=state.settings.cycleDay; if($("settings-advance-val")) $("settings-advance-val").value=Number(state.salary.advanceAmount||0).toFixed(2); setText("status-profile",state.user?.displayName||state.user?.username||"Ajustar"); setText("status-salary",formatMoney(state.salary.reference)); setText("status-cycle",`Dia ${state.settings.cycleDay}`); setText("status-security",state.security.biometricId?"Biometria Ativa":"Protegido"); settingsSalarySplit=state.salary.hasAdvance?"yes":"no"; updateSalarySplitButtons(); }
function updateSalarySplitButtons(){ document.querySelectorAll("[data-settings-salary-split]").forEach(b=>{ b.classList.toggle("selected",b.dataset.settingsSalarySplit===settingsSalarySplit); }); $("salary-split-info")?.classList.toggle("hidden",settingsSalarySplit!=="yes"); }
function parseMoneyInput(v){ if(v===null||v===undefined) return 0; let t=String(v).trim().replace(/\s/g,""); const hasComma=t.includes(","); const hasDot=t.includes("."); if(hasComma&&hasDot){ if(t.lastIndexOf(",")>t.lastIndexOf(".")){ t=t.replace(/\./g,"").replace(",","."); } else { t=t.replace(/,/g,""); } } else if(hasComma){ t=t.replace(",","."); } const n=Number(t); return Number.isFinite(n)?roundMoney(n):0; }
function bindEvents(){
  $("setup-next-button")?.addEventListener("click",handleSetupNext);
  $("setup-limit-yes")?.addEventListener("click",()=>{ setupLimitHasLimit=true; updateSetupLimitButtons(); });
  $("setup-limit-no")?.addEventListener("click",()=>{ setupLimitHasLimit=false; updateSetupLimitButtons(); });
  $("save-setup-limit-button")?.addEventListener("click",saveSetupLimit);
  $("nav-home-button")?.addEventListener("click",()=>switchTab("home"));
  $("nav-extrato-button")?.addEventListener("click",()=>switchTab("extrato"));
  $("previous-cycle-button")?.addEventListener("click",()=>openHistoryModal());
  $("export-backup-button")?.addEventListener("click",exportBackup);
  $("export-csv-button")?.addEventListener("click",exportCSV);
  $("import-backup-button")?.addEventListener("click",()=>$("import-backup-file")?.click());
  $("import-backup-file")?.addEventListener("change",importBackup);
  $("custom-alert-ok")?.addEventListener("click",()=>closeModal("custom-alert-modal"));
  $("custom-confirm-cancel")?.addEventListener("click",()=>closeModal("custom-confirm-modal"));
  $("custom-confirm-ok")?.addEventListener("click",()=>{ closeModal("custom-confirm-modal"); if(typeof customConfirmCallback==="function") customConfirmCallback(); customConfirmCallback=null; });
  $("toggle-lock-password")?.addEventListener("click",()=>{ const input=$("unlock-password"); if(!input) return; input.type=input.type==="password"?"text":"password"; renderLockPasswordIcon(); });
  $("toggle-hide-balances-button")?.addEventListener("click",toggleHideBalances);
  $("biometric-unlock-icon")?.addEventListener("click",authenticateBiometric);
  $("register-biometrics-button")?.addEventListener("click",registerBiometrics);
  $("forgot-password-button")?.addEventListener("click",openForgotPasswordModal);
  $("confirm-recovery-button")?.addEventListener("click",confirmPasswordRecovery);
  $("setup-recovery-question-button")?.addEventListener("click",openRecoveryQuestionSetupModal);
  $("save-sec-q-button")?.addEventListener("click",saveRecoveryQuestionSetup);
  $("extra-card-trigger")?.addEventListener("click",()=>openModal("extra-modal"));
  $("salary-card-trigger")?.addEventListener("click",()=>{ showScreen("settings"); const p=$("salary-settings"); if(p) p.classList.remove("hidden"); });
  $("edit-expense-origin-trigger")?.addEventListener("click",()=>{ const opts=[{label:"Salário",value:"salary",selected:selectedEditExpenseOrigin==="salary"},{label:"Extra",value:"extra",selected:selectedEditExpenseOrigin==="extra"}]; if(selectedEditExpenseOrigin==="reserve") opts.push({label:"Reserva",value:"reserve",selected:true}); openCustomPicker("Origem",opts,v=>{ selectedEditExpenseOrigin=v; }); });
  $("edit-expense-category-trigger")?.addEventListener("click",()=>{ const opts=state.categories.filter(c=>c.id!=="reserve").map(c=>({label:c.name,value:c.id,selected:c.id===selectedEditExpenseCategory})); openCustomPicker("Categoria",opts,v=>{ selectedEditExpenseCategory=v; }); });
  $("category-icon-trigger")?.addEventListener("click",()=>{ openCustomPicker("Ícone",[{label:"Gasto Fixo",value:"fixed",selected:selectedCategoryIcon==="fixed"},{label:"Reserva",value:"reserve",selected:selectedCategoryIcon==="reserve"},{label:"Medicamentos",value:"medicine",selected:selectedCategoryIcon==="medicine"},{label:"Lazer",value:"leisure",selected:selectedCategoryIcon==="leisure"},{label:"Telefone / Internet",value:"phone",selected:selectedCategoryIcon==="phone"},{label:"Outros",value:"other",selected:selectedCategoryIcon==="other"}],v=>{ selectedCategoryIcon=v; }); });
  document.addEventListener("click",e=>{
    const h=e.target.closest("[data-history-cycle-id]"); if(h){ openHistoryModal(h.dataset.historyCycleId); return; }
    const bh=e.target.closest("[data-back-to-history]"); if(bh){ openHistoryModal(); return; }
    const sc=e.target.closest("[data-setup-cat-index]"); if(sc){ openSetupLimitModal(Number(sc.dataset.setupCatIndex)); return; }
    const ss=e.target.closest("[data-choice='salary-split']"); if(ss){ setupSalarySplit=ss.dataset.value; document.querySelectorAll("[data-choice='salary-split']").forEach(b=>{ b.classList.toggle("selected",b.dataset.value===setupSalarySplit); }); $("setup-advance-container")?.classList.toggle("hidden",setupSalarySplit!=="yes"); return; }
    const cl=e.target.closest("[data-category-limit]"); if(cl){ categoryEditorHasLimit=cl.dataset.categoryLimit==="yes"; document.querySelectorAll("[data-category-limit]").forEach(b=>{ b.classList.toggle("selected",b.dataset.categoryLimit===(categoryEditorHasLimit?"yes":"no")); }); $("category-limit-value-container")?.classList.toggle("hidden",!categoryEditorHasLimit); return; }
    const st=e.target.closest("[data-settings-toggle]"); if(st){ const p=$(st.dataset.settingsToggle); if(p){ const isHidden=p.classList.toggle("hidden"); const chev=st.querySelector(".chevron"); if(chev) chev.style.transform=isHidden?"rotate(0deg)":"rotate(180deg)"; } return; }
    const ec=e.target.closest("[data-edit-category-id]"); if(ec){ openCategoryEditorModal(ec.dataset.editCategoryId); return; }
    const ros=e.target.closest("#reserve-origin-salary-btn"); if(ros){ selectedReserveOrigin="salary"; updateReserveModalOriginButtons(); return; }
    const roe=e.target.closest("#reserve-origin-extra-btn"); if(roe){ selectedReserveOrigin="extra"; updateReserveModalOriginButtons(); return; }
    const eos=e.target.closest("#expense-origin-salary-btn"); if(eos){ selectedExpenseOrigin="salary"; updateExpenseModalOriginButtons(); return; }
    const eoe=e.target.closest("#expense-origin-extra-btn"); if(eoe){ selectedExpenseOrigin="extra"; updateExpenseModalOriginButtons(); return; }
    const sss=e.target.closest("[data-settings-salary-split]"); if(sss){ settingsSalarySplit=sss.dataset.settingsSalarySplit; updateSalarySplitButtons(); return; }
    const oc=e.target.closest("[data-category-open]"); if(oc){ openCategoryDetails(oc.dataset.categoryOpen); return; }
    const ed=e.target.closest("[data-edit-expense-id]"); if(ed){ closeModal("category-modal"); openEditExpenseModal(ed.dataset.editExpenseId); return; }
    const ce=e.target.closest("[data-category-expense]"); if(ce){ const id=ce.dataset.categoryExpense; if(id==="reserve") openReserveModal(); else openExpenseModal(id); return; }
    const cb=e.target.closest("[data-close-modal]"); if(cb){ closeModal(cb.dataset.closeModal); if(cb.dataset.closeModal==="expense-edit-modal") currentEditingExpenseId=null; return; }
    const ap=e.target.closest("[data-appearance-choice]"); if(ap){ saveAppearance(ap.dataset.appearanceChoice); return; }
    const th=e.target.closest("[data-theme-choice]"); if(th){ saveTheme(th.dataset.themeChoice); return; }
  });
  $("unlock-button")?.addEventListener("click",async()=>{ const p=$("unlock-password")?.value; const h=await hashPassword(p); if(h===state.security.passwordHash){ localStorage.setItem("fx_temp_key",h.slice(0,16)); state.security.locked=false; await saveState(); showScreen("main",false); renderApplication(); } else { showElement("unlock-error","Senha incorreta."); } });
  $("save-profile-settings")?.addEventListener("click",saveProfileSettings);
  $("logout-button")?.addEventListener("click",lockApp);
  $("create-category-button")?.addEventListener("click",()=>openCategoryEditorModal());
  $("save-category-button")?.addEventListener("click",saveCategory);
  $("confirm-extra-button")?.addEventListener("click",()=>{ const v=parseMoneyInput($("extra-value")?.value); if(v<=0) return showElement("extra-error","Valor inválido."); state.extra.balance=roundMoney(state.extra.balance+v); saveState(); closeModal("extra-modal"); if(document.activeElement) document.activeElement.blur(); renderApplication(); });
  $("confirm-expense-button")?.addEventListener("click",()=>{ try{ const v=parseMoneyInput($("expense-value").value); const o=selectedExpenseOrigin; const d=$("expense-description").value; launchExpense(currentCategoryId,v,o,d); closeModal("expense-modal"); }catch(err){ showElement("expense-error",err.message); } });
  $("save-expense-edit-button")?.addEventListener("click",saveExpenseEdit);
  $("delete-expense-button")?.addEventListener("click",deleteExpense);
  $("reserve-save-button")?.addEventListener("click",showReserveSaveForm);
  $("reserve-withdraw-button")?.addEventListener("click",showWithdrawForm);
  $("confirm-reserve-button")?.addEventListener("click",confirmReserveSave);
  $("confirm-withdraw-button")?.addEventListener("click",confirmReserveWithdraw);
  $("save-salary-settings")?.addEventListener("click",saveSalarySettings);
  $("save-cycle-settings")?.addEventListener("click",saveCycleSettings);
  $("change-password-button")?.addEventListener("click",()=>openModal("password-modal"));
  $("save-password-button")?.addEventListener("click",saveNewPassword);
  $("delete-all-data-button")?.addEventListener("click",()=>openModal("delete-data-modal"));
  $("confirm-delete-data-button")?.addEventListener("click",deleteAllData);
  $("chart-button")?.addEventListener("click",openChartModal);
  $("settings-button")?.addEventListener("click",()=>showScreen("settings"));
  $("settings-back-button")?.addEventListener("click",()=>showScreen("main"));
  $("lock-button")?.addEventListener("click",lockApp);
}
function switchTab(tab,record=true){ currentTabName=tab; $("tab-home").classList.toggle("hidden",tab!=="home"); $("tab-extrato").classList.toggle("hidden",tab!=="extrato"); $("nav-home-button").classList.toggle("active",tab==="home"); $("nav-extrato-button").classList.toggle("active",tab==="extrato"); if(record) pushNavigationState("tab",tab); }
function openExpenseModal(catId){ if(catId==="reserve"){ openReserveModal(); return; } currentCategoryId=catId; selectedExpenseOrigin="salary"; const cat=state.categories.find(c=>c.id===catId); const name=cat?.name||"Categoria"; if($("expense-modal-title")) $("expense-modal-title").textContent=`Lançar em ${name}`; if($("confirm-expense-button")) $("confirm-expense-button").textContent=`Lançar em ${name}`; $("expense-value").value=""; $("expense-description").value=""; updateExpenseModalOriginButtons(); hideElement("expense-error"); openModal("expense-modal"); }
function updateExpenseModalOriginButtons(){ const s=$("expense-origin-salary-btn"); const e=$("expense-origin-extra-btn"); if(s) s.classList.toggle("selected",selectedExpenseOrigin==="salary"); if(e) e.classList.toggle("selected",selectedExpenseOrigin==="extra"); setText("expense-salary-available",formatMoneyOrMask(getSalaryBalance())); setText("expense-extra-available",formatMoneyOrMask(getExtraBalance())); }
function showScreen(name,record=true){ currentScreenName=name; Object.values(screens).forEach(s=>s?.classList.add("hidden")); screens[name]?.classList.remove("hidden"); if(record) pushNavigationState("screen",name); }
function openModal(id){ $(id)?.classList.remove("hidden"); pushNavigationState("modal",id); }
function closeModal(id){ $(id)?.classList.add("hidden"); }
function roundMoney(v){ return Math.round((Number(v)+Number.EPSILON)*100)/100); }
function formatMoney(v){ return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v); }
function formatMoneyOrMask(v){ return state&&state.settings&&state.settings.hideBalances?"R$ •••••":formatMoney(v); }
function setText(id,t){ if($(id)) $(id).textContent=t; }
function showElement(id,msg){ const el=$(id); if(el){ if(msg) el.textContent=msg; el.classList.remove("hidden"); } }
function hideElement(id){ $(id)?.classList.add("hidden"); }
function createId(){ return Date.now().toString(36)+Math.random().toString(36).slice(2,7); }
